### ISSUE TITLE
The (no really) final edits

### ISSUE THREAD

**Issue by embruna** [BrunaLab/HeliconiaDemography#68]
In addition to the committed changes, a few small things to deal with. Line numbers refer to the word doc 

1. line 245: should we cite other r packages? tidyverse? others used for viz?
2. line 291 "almost 40% higher". Shouldn't this be 25% higher? 0.4 * 1.25 = 0.5
3. . line 323: should this be 1999? or did you mean first "transition year" 1998-1999?
4. I found lines 325-328 a bit out of place.
5. Citation fixes: 
- aguirre 2021: lower case t after colon
- beguria 2017: [manual]? should this be a website?
- bianchi 2013: lower case title words
- bruna 2005: lower case title words
- evers et al: correct volume issue pages or in press
- janssen 2921: doi has duplicated https/doi
- McKee 1993 - remove january from year, needs volume/ pages numbers or url 
- Payton 2003: journal missing
- r core team: vienna needed?
- Scott 2021: volume issue and page numbers or in press
- uriarte 2018: change journal name from short to regular (spell out global change biology)

**Comment by Aariq** [comment]
we should cite other packages, my twitter thread made me realize this.  Probably `gratia` and `ggplot2` for visualization.

**Comment by Aariq** [comment]
>I found lines 325-328 a bit out of place.

Not entirely sure what you mean here (line numbers have shifted).  The last few sentences of the "survival" paragraph?
